version: '3'

services:
  app:
    build: .
    image: app:1.0
    container_name: app
    ports:
      - '8080:8080'
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'order'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql